Repository woowa-techcamp-2020/market-15, pull requests merged in 2020-07, with the labels that each got.

#22 Feature/20 login api
  .gitignore
  src/config/db.js
  src/controllers/user/index.js
  src/controllers/user/user-ctrl.js
  src/model/index.js
Labels: back-end, feature

#24 Feature/#19 sign up api
  .gitignore
  app.js
  public/javascripts/SignUpTest.js
  src/config/db.js
  src/controllers/index.js
  src/controllers/user/index.js
  src/controllers/user/user-ctrl.js
  src/model/index.js
  src/model/user.js
  src/routes/index.js
  src/views/join-test.pug
  src/views/main-page.pug
Labels: back-end, feature

#27 Feature/26 safely save password
  public/javascripts/SignUpTest.js
  src/config/db.js
  src/controllers/user/user-ctrl.js
  src/model/user.js
  src/views/join-test.pug
Labels: back-end, feature

#25 Feature/21 duplicate api
  src/controllers/user/index.js
  src/controllers/user/user-ctrl.js
Labels: back-end, feature

#29 Feature/1 - 색상 변수 값 조정 및 주석 작성
  public/stylesheets/scss/_definitions.scss
Labels: enhancement

#33 Feature/1 signup markup
  public/stylesheets/scss/_definitions.scss
  public/stylesheets/scss/reset.scss
  public/stylesheets/scss/signup.scss
  src/routes/index.js
  src/views/join-page.pug
Labels: back-end, feature

#31 Feature/23 login session
  .gitignore
  app.js
  package-lock.json
  package.json
  src/controllers/user/user-ctrl.js
Labels: back-end, feature

#41 [#10] feat(signup) - 약관 체크박스 입력 이벤트 처리
  public/javascripts/pages/JoinPage.js
  src/views/join-page.pug
Labels: feature, front-end

#42 Feature/9 map api
  public/javascripts/pages/JoinPage.js
  public/javascripts/utils/constants.js
  public/stylesheets/scss/signup.scss
  src/views/join-page.pug
Labels: feature, front-end

#44 Feature/34 signup js donguk
  public/javascripts/components/join/AddressForm.js
  public/javascripts/components/join/TermForm.js
  public/javascripts/components/join/index.js
  public/javascripts/pages/JoinPage.js
  public/javascripts/utils/constants.js
Labels: enhancement, feature, fix, front-end

#40 Feature/38 login process
  public/javascripts/apis/api.js
  public/javascripts/pages/LoginPage.js
  public/javascripts/utils/constants.js
  public/stylesheets/scss/login.scss
  src/controllers/user/user-ctrl.js
  src/views/login-page.pug
Labels: feature, fix, front-end
